name: vcm-report-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - sqlalchemy
  - psycopg2
  - plotly
  - voila
  - ipywidgets
  - jupyterlab
  - matplotlib-base
  - requests
  - jupyter_contrib_nbextensions
  - nbgitpuller