name: vcm-report-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - sqlalchemy
  - psycopg2
  - plotly
  - voila>=0.2.11
  - ipywidgets==7.7.2
  - jupyterlab_widgets
  - jupyter_contrib_nbextensions
  - widgetsnbextension